### ISSUE TITLE
Modal keyboard navigation broken

### ISSUE THREAD

**Issue by davidrleonard** [predixdesignsystem/px-modal#32]
The focus trap/keyboard navigation behavior of the modal no longer works. This is a regression introduced by 185e9d399a2a3f88eb0aaa8ed707ff06e8831cec. It has to do with this bit of code:

https://github.com/PredixDev/px-modal/blob/8f5911e2838072ef1bbeb96e599423dc9aee5936/px-modal.html#L281

Calling `refit()` directly after the modal opens but before it animates in cancels the animation. That means we never call `_handleTransitionEnd()` from the animationend event listener. I'll file a related issue for the animation being cancelled. We were initiating the focus trap after the animation ended to ensure the buttons were visible before we focused them.

### Steps to reproduce

1. Create a simple modal:

```html
<px-modal
    header-text="Magna Adipiscing"
    body-text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    accept-text="Submit"
    reject-text="Cancel"
    open-trigger="{{openTrigger}}">
</px-modal>
<px-modal-trigger type="open" trigger="{{openTrigger}}">
  <button>Open modal</button>
</px-modal-trigger>
```

2. Open the modal

**Expected behavior:** When the modal opens the first button ("Cancel") should be focused. When the user hits the tab key, the focus should move to the submit button.

**Actual behavior:** Nothing is focused. The user must tab through the whole application until they reach the cancel button's tab location in the DOM.

3. Press the `ESC` key without tabbing into the modal

**Expected behavior:** Pressing escape closes the modal

**Actual behavior:** The modal is not closed, because focus is not trapped

### Environment

Component: px-modal v3.2.2
Browser: Chrome 64
OS: OSX 10.12

**Comment by MichaelZaporozhets** [comment]
This issue has been resolved.
