### ISSUE TITLE
Modal enter animation broken

### ISSUE THREAD

**Issue by davidrleonard** [predixdesignsystem/px-modal#33]
Related to #32.

When the modal is opened, it no longer transitions into visibility. It just snaps in. The following code should create a transition effect:

https://github.com/PredixDev/px-modal/blob/8f5911e2838072ef1bbeb96e599423dc9aee5936/sass/px-modal.scss#L42-L44

This is a regression introduced by 185e9d399a2a3f88eb0aaa8ed707ff06e8831cec. It has to do with this bit of code:

https://github.com/PredixDev/px-modal/blob/8f5911e2838072ef1bbeb96e599423dc9aee5936/px-modal.html#L281

Calling `refit()` directly after the modal opens but before it animates in cancels the animation. See related #32.

### Steps to reproduce

1. Create a simple modal:

```html
<px-modal
    header-text="Magna Adipiscing"
    body-text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    accept-text="Submit"
    reject-text="Cancel"
    open-trigger="{{openTrigger}}">
</px-modal>
<px-modal-trigger type="open" trigger="{{openTrigger}}">
  <button>Open modal</button>
</px-modal-trigger>
```

2. Open the modal

**Expected behavior:** The modal animates in from invisible to visible according to its CSS transition rules for background-color, visibility, and opacity.

**Actual behavior:** The modal does not animate and snaps into visibility.

3. Dismiss the modal. It correctly fades out of visibility.

### Environment

Component: px-modal v3.2.2
Browser: Chrome 64
OS: OSX 10.12

**Comment by MichaelZaporozhets** [comment]
I have tested this and it appears to be resolved. I will close this issue for now. Please let us know if you can still reproduce this issue.
